[project]
name = "mlops-zoomcamp-zachho9"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hyperopt>=0.3.0",
    "matplotlib>=3.11.2",
    "mlflow>=3.16.0",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]
